apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels: {{ .Values.db.name }}
spec:
  ports:
  - port: {{ .Values.db.ports.containerPort }}
  selector:
    app: {{ .Values.db.name }}
  clusterIP: None