apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.image.repository }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.db.password }}
        ports:
        - containerPort: {{ .Values.db.ports.containerPort }}
          name: {{ .Values.db.ports.name }}
        volumeMounts:
        - name: {{ .Values.db.volume.mount.name }}
          mountPath: {{ .Values.db.volume.mount.path }}
      volumes:
      - name: {{ .Values.db.volume.mount.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.db.volume.claim.name }}