apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.volume.persistent.name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.db.volume.persistent.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.db.volume.persistent.mountPath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.volume.claim.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.volume.persistent.storage }}