FROM python:3.6

EXPOSE 8000

COPY ./* /usr/src/bkfastapi01

WORKDIR /usr/src/bkfastapi01
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]