name: "infra/dbmysql01 Helm Chart pipeline"

on:
  workflow_dispatch:
    inputs:
      var_def:
        description: "Test input value" 
        default: something
        required: false

jobs:

  build:
    name: Build & push Helm Chart to Artifactory
    
    runs-on: ubuntu-latest

    steps:

      - name: Def environments
        run: |
          echo "githubrunid=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GitHub Run Id: {{ env.githubrunid }}"

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Action Helm create-push-package
        uses: ./.github/templates/helm/create-push-package
        with:
          repository: "projfa01-helm"
          sol_name: "dbmysql01"
          sol_version: "{{ env.githubrunid }}"
          folder_path: "infrarpi"
          environment: "dev"




