name: "infradd/dbmysql01 Helm Chart pipeline"

on:
  workflow_dispatch:
    inputs:
      var_def:
        description: "Test input value" 
        default: something
        required: false

env:
  repository: "projfa01-helm"
  sol_name: "dbmysql01"
  folder_path: "infradd"

jobs:

  build:
    name: Build & push Helm Chart to Artifactory
    
    runs-on: ubuntu-latest

    env:
      environment: "dev"

    steps:

      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Action Helm create-push-package
        uses: ./.github/templates/helm/create-push-package
        with:
          repository: ${{ env.repository }}
          sol_name: ${{ env.sol_name }}
          sol_version: $GITHUB_RUN_ID
          folder_path: ${{ env.folder_path }}
          environment: ${{ env.environment }}
          art_user: ${{ secrets.ARTIFACTORY_USER }}
          art_apikey: ${{ secrets.ARTIFACTORY_APIKEY }}





