name: "bkfastapi01 build docker pipeline"

on:
  workflow_dispatch:
    inputs:
      var_def:
        description: "Test input value" 
        default: something
        required: false

env:
  repository_tenant: mfurones01.jfrog.io
  repository: projfa01-docker
  sol_name: "bkfastapi01"
  sol_version: $GITHUB_RUN_ID
  folder_path: "bkfastapi01"


jobs:

  build:
    name: Build & push docker image to Artifactory
    
    runs-on: ubuntu-latest

    env:
      environment: "dev"
      
    steps:

      - name: Def environments
        run: |
          echo "sol_version=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GitHub Run Id: {{ env.sol_version }}"

      - name: checkout bkfastapi01 folder
        uses: Bhacaz/checkout-files@v1
        with:
          files: ${{ env.folder_path }}
          token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.repository_tenant }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_APIKEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./${{ env.folder_path }}/dockerfile/dockerfile
          push: true
          tags: |
            ${{ env.repository_tenant }}/${{ env.repository }}-${{ env.environment }}/${{ env.folder_path }}/${{ env.sol_name }}:latest
            ${{ env.repository_tenant }}/${{ env.repository }}-${{ env.environment }}/${{ env.folder_path }}/${{ env.sol_name }}:${{ env.sol_version }}