name: "bkfastapi01 build docker pipeline"

on:
  workflow_dispatch:
    inputs:
      repository_tenant:
        description: "Artifactory Repo Tenant Name" 
        default: mfurones01.jfrog.io
        required: false
      repository:
        description: "Artifactory Virtual Repo" 
        default: projfa01-docker
        required: false

jobs:

  build:
    name: Build & push docker image to Artifactory
    
    runs-on: ubuntu-latest

    steps:

      - name: Def environments
        run: |
          echo "githubrunid=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GitHub Run Id: {{ env.githubrunid }}"

      - name: checkout bkfastapi01 folder
        uses: Bhacaz/checkout-files@v1
        with:
          files: bkfastapi01
          token: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ${{ github.event.inputs.repository_tenant }}
          username: ${{ secrets.ARTIFACTORY_USER }}
          password: ${{ secrets.ARTIFACTORY_APIKEY }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bkfastapi01/dockerfile/dockerfile
          push: true
          tags: |
            ${{ github.event.inputs.repository_tenant }}/${{ github.event.inputs.repository }}-dev/bkfastapi01/bkfastapi01:latest
            ${{ github.event.inputs.repository_tenant }}/${{ github.event.inputs.repository }}-dev/bkfastapi01/bkfastapi01:${{ env.githubrunid }}