name: "infra/projfa01 NS & common objects Helm Chart pipeline"

on:
  workflow_dispatch:
    inputs:
      var_def:
        description: "Test input value" 
        default: something
        required: false

jobs:

  build:
    name: Build & push Helm Chart to Artifactory
    
    runs-on: ubuntu-latest

    steps:

      - name: Def environments variables
        run: |
          echo "githubrunid=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GitHub Run Id: ${{ github.event.env.githubrunid }}"

      - name: jFrog CLI setup
        uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: checkout Solution folder
        uses: Bhacaz/checkout-files@v1
        with:
          files: "infrarpi"
          token: ${{ github.token }}

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Action Helm create-push-package
        uses: ./.github/templates/helm/create-push-package
        with:
          repository: "projfa01-helm"
          sol_name: "projfa01"
          sol_version: "${{ github.event.env.githubrunid }}"
          folder_path: "infrarpi"
          environment: "dev"
          art_user: ${{ secrets.ARTIFACTORY_USER }}
          art_apikey: ${{ secrets.ARTIFACTORY_APIKEY }}

