name: "to test pipeline"

on:
  workflow_dispatch:
    inputs:
      var_name:
        description: "A description" 
        default: helloworld
        required: false
  push:
    tags:
      - "*"


jobs:

  jobTest1:
    name: Testing the first job
    
    runs-on: ubuntu-latest

    if: ${{ !startsWith(github.ref, 'refs/tags/test01-v*') }}

    steps:

#      - uses: actions/checkout@v1
#      - uses: ./.github/templates/test-nested
#        with:
#          var_some: ${{ github.event.inputs.var_name }}

      - name: run something
        run: |
          echo "No tiene un tag!!!"
          echo "referencia: ${{ github.ref }}"

  jobTest2:
    name: Testing the second job
    
    runs-on: ubuntu-latest
    
    if: ${{ startsWith(github.ref, 'refs/tags/test01-v*') }}

    steps:

#      - uses: actions/checkout@v1
#      - uses: ./.github/templates/test-nested
#        with:
#          var_some: ${{ github.event.inputs.var_name }}

      - name: run something
        run: |
          echo "Siiiii tiene un tag!!!"
          echo "referencia: ${{ github.ref }}"

