name: "to test pipeline"

on:
  workflow_dispatch:
    inputs:
      var_name:
        description: "A description" 
        default: helloworld
        required: false
  push:
    tags:
      - "*"


jobs:

  build:
    name: like a stage
    
    runs-on: ubuntu-latest

    if: !startsWith('refs/tags/test01-v*')

    steps:

#      - uses: actions/checkout@v1
#      - uses: ./.github/templates/test-nested
#        with:
#          var_some: ${{ github.event.inputs.var_name }}

      - name: run something
        run: |
          echo "No tiene un tag!!!"
          echo "referencia: ${{ github.ref }}"

jobs:

  build:
    name: like a stage
    
    runs-on: ubuntu-latest
    
    if: startsWith('refs/tags/test01-v*')

    steps:

#      - uses: actions/checkout@v1
#      - uses: ./.github/templates/test-nested
#        with:
#          var_some: ${{ github.event.inputs.var_name }}

      - name: run something
        run: |
          echo "Siiiii tiene un tag!!!"
          echo "referencia: ${{ github.ref }}"

