name: "to test pipeline"

on:
  workflow_dispatch:
    inputs:
      var_name:
        description: "A description" 
        default: helloworld
        required: false
  push:
    tags:
      - "*"


jobs:

  jobTest1:
    name: Testing the first job
    
    runs-on: ubuntu-latest

    if: ${{ !startsWith(github.ref, 'refs/tags/test01-v') }}
    

    steps:

#      - uses: actions/checkout@v1
#      - uses: ./.github/templates/test-nested
#        with:
#          var_some: ${{ github.event.inputs.var_name }}

      - name: run something
        run: |
          echo "No tiene un tag!!!"
          echo "referencia: ${{ github.ref }}"
          echo "true: ${{ startsWith(github.ref, 'refs/tags/test01-v*') }}"
          echo "false: ${{ !startsWith(github.ref, 'refs/tags/test01-v*') }}"

  jobTest2:
    name: Testing the second job
    
    runs-on: ubuntu-latest
    
    if: ${{ startsWith(github.ref, 'refs/tags/test01-v') }}

    steps:

#      - uses: actions/checkout@v1
#      - uses: ./.github/templates/test-nested
#        with:
#          var_some: ${{ github.event.inputs.var_name }}

      - name: run something
        shell: pwsh
        run: |
          echo "Siiiii tiene un tag!!!"
          echo "referencia: ${{ github.ref }}"
          $rx = '^(refs\/tags\/test01-v)([0-9]+.[0-9]+.[0-9]+)$'
          "${{ github.ref }}" -match $rx
          $Matches
          $Matches[2]
          echo "var_githubref=${Matches}[2]" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
          echo "gitHub Ref: ${{ env.var_githubref }}"


